language: python
python:
  - "3.6"
#  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
#install:
#  - pip install -r requirements.txt
# command to run tests
services:
  - postgresql
script:
  - python3 test_all.py

